### ISSUE TITLE
Fix paths prior to animating

### ISSUE THREAD

**Issue by souporserious** [pratyushcrd/d3-path-morphing#1]
Hello 👋  this is an absolutely amazing plugin for D3! I love how you are able to normalize the path start/end points so animations look natural. I was curious if the path data could be changed beforehand to help with performance, and possibly size, by being able to do this in a node script? After looking at the source this looks like it could take some work, so I wanted to gather your thoughts if you didn't mind 😇

**Comment by pratyushcrd** [comment]
There is a lot scope for performance improvement. Some of the heavy functions are called twice. And many of the functions are created everytime its parent function is called which isnt required.
There is way to shorten down the final path array which I will implement after sorting out all other issues. So, in the final path arrays if the angle for both path isnt changing meaning they in same line, extra path commands could be removed.

**Comment by souporserious** [comment]
It would be awesome if the core of this could be utilized in other libraries. I know in any animation scenario with SVG's it's hard to get the paths to line up properly. Could some sort of function be derived from the current source? It'd be awesome if we could get a standalone `morphPath` function that could be used in things like a transpiler.

**Comment by pratyushcrd** [comment]
The core of the library is independent. When called with two paths it just returns function, where you pass the percentage and get path at that percentage.

**Comment by souporserious** [comment]
Sorry, I didn't notice that. Because of the name, I had assumed it was tied directly to d3. Maybe naming it just `path-morphing` could help get some more outside followers? Anyways, thank you so much for the quick responses!!! I really appreciate all the hard work you've done here 🙏 

I'm going to try and integrate this library into a node script that takes a [Sketch file and returns the path data](https://github.com/souporserious/sketch-to-svg-json-loader). I'm hoping I can fix paths up in node so it doesn't have to be done on the client.
